// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkJAZSMww90Mo6_YlaMvOBMb8ozvpLal0',
    appId: '1:15864129859:web:af9ad3f830a2e4f16e27f6',
    messagingSenderId: '15864129859',
    projectId: 'whatsapp-flutter-6a539',
    authDomain: 'whatsapp-flutter-6a539.firebaseapp.com',
    databaseURL: 'https://whatsapp-flutter-6a539-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-flutter-6a539.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtnMcv_PqgfZe-psmAwNLqsrHdgpUHRFI',
    appId: '1:15864129859:android:2a5e79319a9c40aa6e27f6',
    messagingSenderId: '15864129859',
    projectId: 'whatsapp-flutter-6a539',
    databaseURL: 'https://whatsapp-flutter-6a539-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-flutter-6a539.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB62TjbhB9fztYSzKAtbe8kYiLf_0fkcj8',
    appId: '1:15864129859:ios:4eabf94b75a3497e6e27f6',
    messagingSenderId: '15864129859',
    projectId: 'whatsapp-flutter-6a539',
    databaseURL: 'https://whatsapp-flutter-6a539-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-flutter-6a539.appspot.com',
    iosClientId: '15864129859-enn616ifpok8k4u2uh48ikfvljrategv.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB62TjbhB9fztYSzKAtbe8kYiLf_0fkcj8',
    appId: '1:15864129859:ios:4eabf94b75a3497e6e27f6',
    messagingSenderId: '15864129859',
    projectId: 'whatsapp-flutter-6a539',
    databaseURL: 'https://whatsapp-flutter-6a539-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-flutter-6a539.appspot.com',
    iosClientId: '15864129859-enn616ifpok8k4u2uh48ikfvljrategv.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
